import { http, HttpResponse } from 'msw'
import type {
  InstructorDashboardData,
  InstructorCohortsData,
  CohortStudentsData,
} from '@/shared/types'

// 기능별 mock — handlers.ts의 import.meta.glob('../features/**/mocks.ts')가 자동 수집(#37).
const ok = <T>(data: T) => HttpResponse.json({ data })

// ── §1 강사 대시보드 (Figma 1268:7456) — 기수별 데이터(칩 선택 시 해당 기수만) ──
const dashboardCohorts = [
  { id: 'da-4', label: 'DA 4기 · 진행 중' },
  { id: 'fe-7', label: 'FE 7기 · 진행 중' },
]

const dashboardByCohort: Record<string, InstructorDashboardData> = {
  // 통합(전체) — 담당 전 기수 합산. 칩 '전체' 선택 시(기본).
  all: {
    instructorName: '박준석',
    cohortCount: 2,
    cohorts: dashboardCohorts,
    kpiGrading: {
      value: 14,
      hint: '수동 채점 9 · 자동 재검토 5',
      badge: '오늘 +3',
    },
    kpiProjects: { value: 3, hint: 'PM 인증 요청 · D+2 1건' },
    kpiSupplements: {
      value: 2,
      hint: '학생 응답 대기 · D+5 1건',
      badge: '긴급',
    },
    priorities: [
      {
        id: 'pri-1',
        type: 'supplement',
        title: '점수 재검토 보완 응답',
        subtitle: '박지훈 · FE 7기',
        dday: 'D+5',
        urgent: true,
        actionLabel: '확인',
        to: '/instructor/cohorts/fe-7/education',
      },
      {
        id: 'pri-2',
        type: 'manual_grading',
        title: '알고리즘 기초 퀴즈 #3 · 5문항 채점 대기',
        subtitle: '김민준 · DA 4기',
        dday: 'D+1',
        urgent: false,
        actionLabel: '채점 시작',
        to: '/instructor/quizzes/quiz-algo-3/submissions',
      },
      {
        id: 'pri-3',
        type: 'project_cert',
        title: '추천 영상 큐레이션 PM 인증 요청',
        subtitle: 'DA 4팀 (3명)',
        dday: 'D+2',
        urgent: false,
        actionLabel: '검토',
        to: '/instructor/records/review',
      },
      {
        id: 'pri-5',
        type: 'ts_review',
        title: 'OOM 원인 분석 사례 · 강사 승인 대기',
        subtitle: '박지훈 · FE 7기',
        dday: 'D+1',
        urgent: false,
        actionLabel: '검토',
        to: '/instructor/records/review',
      },
      {
        id: 'pri-6',
        type: 'manual_grading',
        title: '데이터 분석 퀴즈 #2 · 3문항 채점 대기',
        subtitle: '정도윤 · DA 4기',
        dday: 'D+1',
        urgent: false,
        actionLabel: '채점 시작',
        to: '/instructor/quizzes/quiz-algo-3/submissions',
      },
    ],
    shortcuts: {
      quizzes: { badge: 14, hint: '채점 대기 14' },
      students: { hint: 'DA 4기 · FE 7기 통합' },
      reviews: {
        badge: 12,
        hint: '기록 7 + 프로젝트 3 + 트러블슈팅 2',
      },
    },
  },
  'da-4': {
    instructorName: '박준석',
    cohortCount: 2,
    cohorts: dashboardCohorts,
    kpiGrading: {
      value: 9,
      hint: '수동 채점 6 · 자동 재검토 3',
      badge: '오늘 +3',
    },
    kpiProjects: { value: 2, hint: 'PM 인증 요청 · D+2 1건' },
    kpiSupplements: { value: 1, hint: '학생 응답 대기 1건' },
    priorities: [
      {
        id: 'pri-2',
        type: 'manual_grading',
        title: '알고리즘 기초 퀴즈 #3 · 5문항 채점 대기',
        subtitle: '김민준 · DA 4기',
        dday: 'D+1',
        urgent: false,
        actionLabel: '채점 시작',
        to: '/instructor/quizzes/quiz-algo-3/submissions',
      },
      {
        id: 'pri-3',
        type: 'project_cert',
        title: '추천 영상 큐레이션 PM 인증 요청',
        subtitle: 'DA 4팀 (3명)',
        dday: 'D+2',
        urgent: false,
        actionLabel: '검토',
        to: '/instructor/records/review',
      },
      {
        id: 'pri-6',
        type: 'manual_grading',
        title: '데이터 분석 퀴즈 #2 · 3문항 채점 대기',
        subtitle: '정도윤 · DA 4기',
        dday: 'D+1',
        urgent: false,
        actionLabel: '채점 시작',
        to: '/instructor/quizzes/quiz-algo-3/submissions',
      },
    ],
    shortcuts: {
      quizzes: { badge: 9, hint: '채점 대기 9' },
      students: { hint: 'DA 4기 24명' },
      reviews: {
        badge: 7,
        hint: '기록 4 + 프로젝트 2 + 트러블슈팅 1',
      },
    },
  },
  'fe-7': {
    instructorName: '박준석',
    cohortCount: 2,
    cohorts: dashboardCohorts,
    kpiGrading: { value: 5, hint: '수동 채점 3 · 자동 재검토 2' },
    kpiProjects: { value: 1, hint: 'PM 인증 요청 1건' },
    kpiSupplements: {
      value: 1,
      hint: '학생 응답 대기 · D+5 1건',
      badge: '긴급',
    },
    priorities: [
      {
        id: 'pri-1',
        type: 'supplement',
        title: '점수 재검토 보완 응답',
        subtitle: '박지훈 · FE 7기',
        dday: 'D+5',
        urgent: true,
        actionLabel: '확인',
        to: '/instructor/cohorts/fe-7/education',
      },
      {
        id: 'pri-5',
        type: 'ts_review',
        title: 'OOM 원인 분석 사례 · 강사 승인 대기',
        subtitle: '박지훈 · FE 7기',
        dday: 'D+1',
        urgent: false,
        actionLabel: '검토',
        to: '/instructor/records/review',
      },
    ],
    shortcuts: {
      quizzes: { badge: 5, hint: '채점 대기 5' },
      students: { hint: 'FE 7기 18명' },
      reviews: {
        badge: 5,
        hint: '기록 3 + 프로젝트 1 + 트러블슈팅 1',
      },
    },
  },
}

// ── §2 담당 과정/기수 (Figma 1324:9636) ──
const cohorts: InstructorCohortsData = {
  total: 5,
  operating: 2,
  upcoming: 0,
  ended: 3,
  summary: {
    operatingCourses: { value: 2, hint: 'DA 4기 · FE 7기' },
    students: { value: 42, hint: 'DA 24 + FE 18 · 위험 3' },
    gradingPending: { value: 14, hint: 'DA 9 + FE 5 · 오늘 +3' },
    reviewPending: { value: 12, hint: '기록 7 + 프로젝트 3 + 트러블 2' },
  },
  rows: [
    {
      id: 'da-4',
      name: 'DA 4기',
      subtitle: '데이터 분석 · 4회차',
      period: '2026.03.01 ~ 2026.05.31',
      dday: 'D-12',
      role: 'lead',
      students: 24,
      riskCount: 2,
      evalSummary: '미응시 3 · 제출 18',
      evalPending: '채점 대기 9',
      reviewSummary: '기록 4 · 프로젝트 2 · 트러블 1',
      reviewPending: '대기 7건',
      status: 'operating',
    },
    {
      id: 'fe-7',
      name: 'FE 7기',
      subtitle: '프론트엔드 · 7회차',
      period: '2026.04.01 ~ 2026.06.30',
      dday: 'D-42',
      role: 'assist',
      students: 18,
      riskCount: 1,
      evalSummary: '미응시 5 · 제출 12',
      evalPending: '채점 대기 5',
      reviewSummary: '기록 3 · 프로젝트 1 · 트러블 1',
      reviewPending: '대기 5건',
      status: 'operating',
    },
    {
      id: 'da-3',
      name: 'DA 3기',
      subtitle: '데이터 분석 · 3회차',
      period: '2025.09.01 ~ 2025.12.20',
      dday: '종료',
      role: 'lead',
      students: 22,
      riskCount: 0,
      evalSummary: '미응시 0 · 제출 22',
      evalPending: '채점 완료',
      reviewSummary: '기록 0 · 프로젝트 0 · 트러블 0',
      reviewPending: '대기 0건',
      status: 'ended',
    },
    {
      id: 'fe-6',
      name: 'FE 6기',
      subtitle: '프론트엔드 · 6회차',
      period: '2025.10.01 ~ 2026.01.15',
      dday: '종료',
      role: 'assist',
      students: 20,
      riskCount: 0,
      evalSummary: '미응시 0 · 제출 20',
      evalPending: '채점 완료',
      reviewSummary: '기록 0 · 프로젝트 0 · 트러블 0',
      reviewPending: '대기 0건',
      status: 'ended',
    },
    {
      id: 'da-2',
      name: 'DA 2기',
      subtitle: '데이터 분석 · 2회차',
      period: '2025.03.01 ~ 2025.06.30',
      dday: '종료',
      role: 'lead',
      students: 21,
      riskCount: 0,
      evalSummary: '미응시 0 · 제출 21',
      evalPending: '채점 완료',
      reviewSummary: '기록 0 · 프로젝트 0 · 트러블 0',
      reviewPending: '대기 0건',
      status: 'ended',
    },
  ],
}

// ── §3 수강생 목록 (Figma 1330:9675) ──
const students: CohortStudentsData = {
  cohortLabel: 'DA 4기',
  total: 24,
  riskTotal: 3,
  rows: [
    {
      id: 'stu-1',
      name: '박지훈',
      emailUuid: 'park.jh@playdata · ghi-9012',
      cohortLabel: 'FE 7기',
      certStatus: 'changes_requested',
      quizAvg: '평균 78.2',
      quizDetail: '미응시 0 · 채점 1',
      recordApproved: '승인 8',
      recordDetail: '대기 0 · 반려 1',
      projectStatus: 'reviewing',
      riskFlags: ['점수 재검토'],
    },
    {
      id: 'stu-2',
      name: '이서연',
      emailUuid: 'lee.sy@playdata · def-5678',
      cohortLabel: 'DA 4기',
      certStatus: 'reviewing',
      quizAvg: '평균 84.7',
      quizDetail: '미응시 1 · 채점 2',
      recordApproved: '승인 12',
      recordDetail: '대기 1 · 반려 0',
      projectStatus: 'certified',
      riskFlags: [],
    },
    {
      id: 'stu-3',
      name: '한소율',
      emailUuid: 'han.sy@playdata · pqr-1357',
      cohortLabel: 'FE 7기',
      certStatus: 'reviewing',
      quizAvg: '평균 76.1',
      quizDetail: '미응시 2 · 채점 0',
      recordApproved: '승인 9',
      recordDetail: '대기 1 · 반려 0',
      projectStatus: 'certified',
      riskFlags: ['미승인 산출물'],
    },
    {
      id: 'stu-4',
      name: '정도윤',
      emailUuid: 'jung.dy@playdata · mno-7890',
      cohortLabel: 'DA 4기',
      certStatus: 'requested',
      quizAvg: '평균 79',
      quizDetail: '미응시 1 · 채점 1',
      recordApproved: '승인 7',
      recordDetail: '대기 0 · 반려 1',
      projectStatus: 'drafting',
      riskFlags: ['개인정보'],
    },
    {
      id: 'stu-5',
      name: '김민준',
      emailUuid: 'kim.mj@playdata · abc-1234',
      cohortLabel: 'DA 4기',
      certStatus: 'requested',
      quizAvg: '평균 81.5',
      quizDetail: '미응시 1 · 채점 0',
      recordApproved: '승인 10',
      recordDetail: '대기 0 · 반려 0',
      projectStatus: 'drafting',
      riskFlags: [],
    },
    {
      id: 'stu-6',
      name: '윤재호',
      emailUuid: 'yoon.jh@playdata · stu-2468',
      cohortLabel: 'FE 7기',
      certStatus: 'reviewing',
      quizAvg: '평균 88.3',
      quizDetail: '미응시 0 · 채점 0',
      recordApproved: '승인 11',
      recordDetail: '대기 0 · 반려 0',
      projectStatus: 'reviewing',
      riskFlags: [],
    },
    {
      id: 'stu-7',
      name: '강민서',
      emailUuid: 'kang.ms@playdata · vwx-3691',
      cohortLabel: 'DA 4기',
      certStatus: 'certified',
      quizAvg: '평균 90.1',
      quizDetail: '미응시 0 · 채점 0',
      recordApproved: '승인 14',
      recordDetail: '대기 0 · 반려 0',
      projectStatus: 'certified',
      riskFlags: [],
    },
    {
      id: 'stu-8',
      name: '오세훈',
      emailUuid: 'oh.sh@playdata · yz-4812',
      cohortLabel: 'FE 7기',
      certStatus: 'requested',
      quizAvg: '평균 72.4',
      quizDetail: '미응시 3 · 채점 0',
      recordApproved: '승인 5',
      recordDetail: '대기 2 · 반려 0',
      projectStatus: 'drafting',
      riskFlags: ['결측'],
    },
    {
      id: 'stu-9',
      name: '임가은',
      emailUuid: 'lim.ge@playdata · abc-5927',
      cohortLabel: 'DA 4기',
      certStatus: 'reviewing',
      quizAvg: '평균 85.0',
      quizDetail: '미응시 0 · 채점 1',
      recordApproved: '승인 10',
      recordDetail: '대기 1 · 반려 0',
      projectStatus: 'reviewing',
      riskFlags: [],
    },
    {
      id: 'stu-10',
      name: '조현우',
      emailUuid: 'jo.hw@playdata · def-6048',
      cohortLabel: 'FE 7기',
      certStatus: 'drafting',
      quizAvg: '평균 80.6',
      quizDetail: '미응시 1 · 채점 0',
      recordApproved: '승인 6',
      recordDetail: '대기 0 · 반려 0',
      projectStatus: 'drafting',
      riskFlags: [],
    },
    {
      id: 'stu-11',
      name: '백지민',
      emailUuid: 'baek.jm@playdata · ghi-7159',
      cohortLabel: 'DA 4기',
      certStatus: 'changes_requested',
      quizAvg: '평균 77.8',
      quizDetail: '미응시 0 · 채점 1',
      recordApproved: '승인 9',
      recordDetail: '대기 0 · 반려 2',
      projectStatus: 'reviewing',
      riskFlags: ['점수 재검토'],
    },
    {
      id: 'stu-12',
      name: '신우진',
      emailUuid: 'shin.wj@playdata · jkl-8260',
      cohortLabel: 'FE 7기',
      certStatus: 'certified',
      quizAvg: '평균 91.5',
      quizDetail: '미응시 0 · 채점 0',
      recordApproved: '승인 13',
      recordDetail: '대기 0 · 반려 0',
      projectStatus: 'certified',
      riskFlags: [],
    },
    {
      id: 'stu-13',
      name: '권나영',
      emailUuid: 'kwon.ny@playdata · mno-9371',
      cohortLabel: 'DA 4기',
      certStatus: 'requested',
      quizAvg: '평균 83.2',
      quizDetail: '미응시 1 · 채점 0',
      recordApproved: '승인 8',
      recordDetail: '대기 1 · 반려 0',
      projectStatus: 'drafting',
      riskFlags: [],
    },
  ],
}

// 담당 기수 없음 시연용 변형 (Figma 2750:1974) — instructor-new@* 계정으로 로그인 시 반환.
const dashboardNoCohort: InstructorDashboardData = {
  ...dashboardByCohort['da-4'],
  instructorName: '신규',
  cohortCount: 0,
  cohorts: [],
  priorities: [],
}

// persist된 auth(localStorage 'lms-auth')에서 이메일을 읽어 mock 분기.
// MSW 핸들러는 앱 컨텍스트에서 실행되므로 localStorage 접근 가능.
function isNewInstructor() {
  try {
    const raw = localStorage.getItem('lms-auth')
    if (!raw) return false
    const email: string = JSON.parse(raw)?.state?.user?.email ?? ''
    return email.startsWith('instructor-new')
  } catch {
    return false
  }
}

export const handlers = [
  http.get('/api/instructor/dashboard', ({ request }) => {
    if (isNewInstructor()) return ok<InstructorDashboardData>(dashboardNoCohort)
    const cohortId = new URL(request.url).searchParams.get('cohortId')
    return ok<InstructorDashboardData>(
      (cohortId && dashboardByCohort[cohortId]) || dashboardByCohort['all'],
    )
  }),
  http.get('/api/instructor/cohorts', () => ok<InstructorCohortsData>(cohorts)),
  http.get('/api/instructor/cohorts/:cohortId/students', () =>
    ok<CohortStudentsData>(students),
  ),
]
