import { http, HttpResponse } from 'msw'
import type {
  MileageHistoryData,
  MileageOverview,
  MileageProductsData,
} from './types'

// 마일리지 mock — 기능 로컬. 자동 수집 규약: `export const handlers`.
// Figma 내 마일리지(418:1850)·상품 신청(418:1961)·사용 내역(418:2066) 시안 재현.
const ok = <T>(data: T) => HttpResponse.json({ data })

const mockOverview: MileageOverview = {
  balance: '128,400',
  balanceSub: '이번 달 적립 · 다음 만료 7월 후 2,000M',
  stats: [
    {
      key: 'balance',
      label: '보유 마일리지',
      value: '128,400',
      unit: 'M',
      sub: '최근 적립 +20,000M · 03시간 전',
      tone: 'success',
      barPct: 43,
      delta: { label: '▲ +18K', tone: 'success' },
    },
    {
      key: 'used',
      label: '이번 달 사용',
      value: '42,000',
      unit: 'M',
      sub: '도서 구매 1건 · 강의 1건',
      tone: 'accent',
      barPct: 22,
    },
    {
      key: 'requests',
      label: '구매 요청',
      value: '3',
      unit: '건',
      sub: '승인 대기 1건 · 승인 완료 2건',
      tone: 'warning',
      barPct: 26,
      delta: { label: '대기 1', tone: 'warning' },
    },
    {
      key: 'limit',
      label: '사용 한도',
      value: '71',
      unit: '%',
      sub: '도서·강의 한도 기준 · 잔여 29%',
      tone: 'info',
      barPct: 71,
    },
  ],
  ledger: [
    {
      id: 'l1',
      label: '프로젝트 인증 보상',
      date: '2026-05-14',
      amount: '+20,000M',
      status: { label: '적립', tone: 'success' },
      positive: true,
    },
    {
      id: 'l2',
      label: '도서 구매 신청',
      date: '2026-05-13',
      amount: '-32,000M',
      status: { label: '대기', tone: 'warning' },
      positive: false,
    },
    {
      id: 'l3',
      label: '주간 출석 보너스',
      date: '2026-05-10',
      amount: '+5,000M',
      status: { label: '적립', tone: 'success' },
      positive: true,
    },
    {
      id: 'l4',
      label: '기프티콘 구매',
      date: '2026-05-09 · 승인 완료',
      amount: '-10,000M',
      status: { label: '사용', tone: 'accent' },
      positive: false,
    },
    {
      id: 'l5',
      label: 'PLAY 챌린지 보상',
      date: '2026-05-08',
      amount: '+3,000M',
      status: { label: '적립', tone: 'success' },
      positive: true,
    },
  ],
  products: [
    {
      name: '도서 구매',
      limit: '잔여 한도 68,000M',
      tone: 'brand',
      icon: 'book',
      barPct: 9,
    },
    {
      name: '온라인 강의',
      limit: '잔여 한도 120,000M',
      tone: 'accent',
      icon: 'video',
      barPct: 11,
    },
    {
      name: '기프티콘',
      limit: '잔여 한도 30,000M',
      tone: 'warning',
      icon: 'gift',
      barPct: 16,
    },
  ],
  limits: [
    {
      label: '도서',
      used: 42000,
      total: 100000,
      status: { label: '여유', tone: 'success' },
      tone: 'success',
    },
    {
      label: '온라인 강의',
      used: 40000,
      total: 200000,
      status: { label: '여유', tone: 'info' },
      tone: 'info',
    },
    {
      label: '기프티콘',
      used: 30000,
      total: 50000,
      status: { label: '주의 60% 사용', tone: 'warning' },
      tone: 'warning',
    },
  ],
}

const mockProducts: MileageProductsData = {
  balance: '128,400',
  inProgress: 3,
  filters: [
    { key: 'all', label: '전체', count: 6 },
    { key: 'gift', label: '기프티콘', count: 2 },
    { key: 'book', label: '도서', count: 2 },
    { key: 'course', label: '온라인 강의', count: 2 },
  ],
  products: [
    {
      id: 'p1',
      name: '교보문고 도서 구매',
      badges: [
        { label: '도서', tone: 'success' },
        { label: '입력', tone: 'info' },
      ],
      priceType: '유연가',
      desc: '개별 도서 링크 + 가격 입력 후 신청',
      limit: '58,000',
      tone: 'success',
    },
    {
      id: 'p2',
      name: '인프런 강의 구매',
      badges: [
        { label: '온라인 강의', tone: 'info' },
        { label: '입력', tone: 'info' },
      ],
      priceType: '유연가',
      desc: '강의 링크 + 가격 입력 후 신청',
      limit: '120,000',
      tone: 'info',
    },
    {
      id: 'p3',
      name: '스타벅스 아메리카노',
      badges: [
        { label: '기프티콘', tone: 'warning' },
        { label: '고정가', tone: 'accent' },
      ],
      priceType: '고정가',
      price: '10,000M',
      desc: '교환권 즉시 발급 · 자동 승인',
      limit: '30,000',
      tone: 'warning',
    },
    {
      id: 'p4',
      name: '개발 서적 세트',
      badges: [
        { label: '도서', tone: 'success' },
        { label: '고정가', tone: 'accent' },
      ],
      priceType: '고정가',
      price: '45,000M',
      desc: '입문 투 매니지 강좌 (3편 세트)',
      limit: '58,000',
      tone: 'success',
    },
    {
      id: 'p5',
      name: '클라우드 실습 크레딧',
      badges: [
        { label: '온라인 강의', tone: 'info' },
        { label: '고정가', tone: 'accent' },
      ],
      priceType: '고정가',
      price: '35,000M',
      desc: 'AWS 실습 크레딧 즉시 지급',
      limit: '120,000',
      tone: 'info',
    },
    {
      id: 'p6',
      name: '편의점 모바일 쿠폰',
      badges: [
        { label: '기프티콘', tone: 'warning' },
        { label: '고정가', tone: 'accent' },
      ],
      priceType: '고정가',
      price: '5,000M',
      desc: 'GS25·CU 통합 모바일 쿠폰',
      limit: '30,000',
      tone: 'warning',
    },
  ],
}

const mockHistory: MileageHistoryData = {
  stats: [
    {
      key: 'earn',
      label: '총 적립',
      value: '+28,000',
      unit: 'M',
      sub: '최근 30일 · 4건',
      tone: 'success',
    },
    {
      key: 'spend',
      label: '총 사용',
      value: '-10,000',
      unit: 'M',
      sub: '최근 30일 · 1건',
      tone: 'accent',
    },
    {
      key: 'pending',
      label: '진행 중 요청',
      value: '1',
      unit: '건',
      sub: '대기 · -32,000M 매니저 확인 중',
      tone: 'warning',
    },
    {
      key: 'rejected',
      label: '반려',
      value: '1',
      unit: '건',
      sub: '조처 필요 · -45,000M 링크 재제출 필요',
      tone: 'danger',
    },
  ],
  filters: [
    { key: 'all', label: '전체', count: 6 },
    { key: 'earn', label: '적립', count: 3 },
    { key: 'spend', label: '사용', count: 1 },
    { key: 'request', label: '구매 요청', count: 2 },
    { key: 'pending', label: '승인 대기', count: 1 },
    { key: 'rejected', label: '반려', count: 1 },
  ],
  rows: [
    {
      date: '2026-05-14',
      kind: { label: '적립', tone: 'success' },
      content: '프로젝트 인증 보상',
      amount: '+20,000M',
      positive: true,
      status: { label: '완료', tone: 'success' },
      memo: '자동 지급',
    },
    {
      date: '2026-05-13',
      kind: { label: '구매 요청', tone: 'info' },
      content: '도서 구매 신청 — 클린 아키텍처 외 2권',
      amount: '-32,000M',
      positive: false,
      status: { label: '대기', tone: 'warning' },
      memo: '매니저 확인 중 · D+1',
    },
    {
      date: '2026-05-10',
      kind: { label: '적립', tone: 'success' },
      content: '주간 출석 보너스',
      amount: '+5,000M',
      positive: true,
      status: { label: '완료', tone: 'success' },
      memo: '출석률 100%',
    },
    {
      date: '2026-05-09',
      kind: { label: '사용', tone: 'accent' },
      content: '기프티콘 구매 — 스타벅스 아메리카노',
      amount: '-10,000M',
      positive: false,
      status: { label: '완료', tone: 'success' },
      memo: '승인 완료 · 즉시 발급',
    },
    {
      date: '2026-05-08',
      kind: { label: '적립', tone: 'success' },
      content: 'PLAY 챌린지 보상',
      amount: '+3,000M',
      positive: true,
      status: { label: '완료', tone: 'success' },
      memo: '상위 10% 입상',
    },
    {
      date: '2026-05-06',
      kind: { label: '구매 요청', tone: 'info' },
      content: '온라인 강의 구매 — Spring 마스터',
      amount: '-45,000M',
      positive: false,
      status: { label: '반려', tone: 'danger' },
      memo: '링크 재제출 필요 · 재신청 요청',
    },
  ],
  shownLabel: '최근 30일 6건 표시 · 총 누적 28건',
}

export const handlers = [
  http.get('/api/student/mileage', () => ok(mockOverview)),
  http.get('/api/student/mileage/products', () => ok(mockProducts)),
  http.get('/api/student/mileage/history', () => ok(mockHistory)),
]
