import { http, HttpResponse } from 'msw'
import type { SettingsHubData, OpsAccountsData } from '@/shared/types'
import type { SettingsAuditData } from './settingsAudit.types'

// 기능별 mock — handlers.ts의 import.meta.glob('../features/**/mocks.ts')가 자동 수집(#37).
const ok = <T>(data: T) => HttpResponse.json({ data })

// ── 설정 허브 (Figma 1284:8852) ──
const hub: SettingsHubData = {
  lastChange: { at: '09:05', by: '김매니저' },
  accounts: {
    rows: [
      { label: '매니저', value: '8명' },
      { label: '강사', value: '27명' },
      { label: '멘토', value: '42명' },
      { label: '최근 변경', value: '09:05 김매니저' },
    ],
  },
  hrdKey: {
    rows: [
      { label: '등록된 Key', value: '2개' },
      { label: '만료 임박', value: '1건 (D-14)' },
      { label: '폐기 이력', value: '3건' },
      { label: '마지막 발급', value: '05-12 이매니저' },
    ],
  },
  courseConfig: {
    rows: [
      { label: '진행 중 과정', value: '12개' },
      { label: '기능 토글 변경', value: '최근 7일 4건' },
      { label: '인증 정책', value: '과정별 다름' },
      { label: '마지막 변경', value: '05-26 박매니저' },
    ],
  },
  courseAdd: {
    rows: [
      { label: '신규 추가', value: '최근 30일 2개' },
      { label: '검색 소스', value: 'HRD-Net' },
      { label: '승인 단계', value: 'HRD 검색 → 매핑 → 생성' },
      { label: '대기 중', value: '0건' },
    ],
  },
  auditLogs: [
    {
      id: 'log-1',
      at: '05-27 09:05',
      actor: '김매니저',
      origin: '계정 관리',
      action: '강사 권한 부여',
      detail: '이지훈 강사',
    },
    {
      id: 'log-2',
      at: '05-26 18:42',
      actor: '박매니저',
      origin: '교육 과정 설정',
      action: '기능 토글 변경',
      detail: 'AI 캠프 22기 · 평판 ON',
    },
    {
      id: 'log-3',
      at: '05-26 14:21',
      actor: '김매니저',
      origin: 'HRD API Key',
      action: '키 교체',
      detail: 'prod-key-2026Q2',
    },
    {
      id: 'log-4',
      at: '05-25 16:08',
      actor: '이매니저',
      origin: '교육 과정 추가',
      action: '신규 과정 생성',
      detail: 'DA 5기',
    },
  ],
}

// ── 계정 관리 (Figma 1284:8597) ──
const accounts: OpsAccountsData = {
  summary: {
    managers: 8,
    managersActive: 8,
    managersInactive: 0,
    instructors: 27,
    instructorNoScope: 2,
    mentors: 42,
    mentorNoTeam: 3,
    inactive: 5,
    inactiveRevoked30d: 2,
    total: 77,
  },
  items: [
    {
      id: 'ops-1',
      name: '이정훈',
      email: 'lee@playdata.io',
      role: 'MANAGER',
      scope: '전체 운영 · 모든 과정·기수',
      status: 'active',
      lastLoginAt: '오늘 09:18',
      isSelf: true,
    },
    {
      id: 'ops-2',
      name: '김매니저',
      email: 'kim@playdata.io',
      role: 'MANAGER',
      scope: '전체 운영 · 모든 과정·기수',
      status: 'active',
      lastLoginAt: '오늘 08:42',
      isSelf: false,
    },
    {
      id: 'ops-3',
      name: '이지훈 강사',
      email: 'instructor.lee@playdata.io',
      role: 'INSTRUCTOR',
      scope: 'AI 캠프 22기 · DA 5기',
      status: 'active',
      lastLoginAt: '어제 18:03',
      isSelf: false,
    },
    {
      id: 'ops-4',
      name: '박강사',
      email: 'instructor.park@playdata.io',
      role: 'INSTRUCTOR',
      scope: '담당 범위 없음',
      status: 'active',
      lastLoginAt: '05-22 14:31',
      isSelf: false,
    },
    {
      id: 'ops-5',
      name: '김효원 멘토',
      email: 'mentor.kim@playdata.io',
      role: 'MENTOR',
      scope: 'AI 캠프 22기 LLM 추천 시스템 팀',
      status: 'active',
      lastLoginAt: '오늘 07:55',
      isSelf: false,
    },
    {
      id: 'ops-6',
      name: '박멘토',
      email: 'mentor.park@playdata.io',
      role: 'MENTOR',
      scope: '팀 배정 없음',
      status: 'invited',
      lastLoginAt: null,
      isSelf: false,
    },
    {
      id: 'ops-7',
      name: '박서연 강사',
      email: 'instructor.seoyeon@playdata.io',
      role: 'INSTRUCTOR',
      scope: 'AI 캠프 21기',
      status: 'active',
      lastLoginAt: '오늘 09:01',
      isSelf: false,
    },
    {
      id: 'ops-8',
      name: '김도윤 강사',
      email: 'instructor.doyun@playdata.io',
      role: 'INSTRUCTOR',
      scope: 'DE 3기',
      status: 'active',
      lastLoginAt: '어제 17:20',
      isSelf: false,
    },
    {
      id: 'ops-9',
      name: '이하준 강사',
      email: 'instructor.hajun@playdata.io',
      role: 'INSTRUCTOR',
      scope: 'AI 캠프 22기',
      status: 'inactive',
      lastLoginAt: '05-10 11:00',
      isSelf: false,
    },
    {
      id: 'ops-10',
      name: '정시우 멘토',
      email: 'mentor.siwoo@playdata.io',
      role: 'MENTOR',
      scope: 'AI 캠프 22기 백엔드 팀',
      status: 'active',
      lastLoginAt: '오늘 08:10',
      isSelf: false,
    },
    {
      id: 'ops-11',
      name: '최예준 멘토',
      email: 'mentor.yejun@playdata.io',
      role: 'MENTOR',
      scope: 'DA 5기 분석 팀',
      status: 'active',
      lastLoginAt: '어제 19:45',
      isSelf: false,
    },
    {
      id: 'ops-12',
      name: '한지호 멘토',
      email: 'mentor.jiho@playdata.io',
      role: 'MENTOR',
      scope: '팀 배정 없음',
      status: 'invited',
      lastLoginAt: null,
      isSelf: false,
    },
    {
      id: 'ops-13',
      name: '오서진 강사',
      email: 'instructor.seojin@playdata.io',
      role: 'INSTRUCTOR',
      scope: 'AI 캠프 20기',
      status: 'inactive',
      lastLoginAt: '04-30 09:00',
      isSelf: false,
    },
    {
      id: 'ops-14',
      name: '윤채원 매니저',
      email: 'manager.chaewon@playdata.io',
      role: 'MANAGER',
      scope: '전체 운영 · 모든 과정·기수',
      status: 'active',
      lastLoginAt: '오늘 07:30',
      isSelf: false,
    },
    {
      id: 'ops-15',
      name: '임지안 멘토',
      email: 'mentor.jian@playdata.io',
      role: 'MENTOR',
      scope: 'DE 3기 데이터 팀',
      status: 'active',
      lastLoginAt: '05-25 14:00',
      isSelf: false,
    },
    {
      id: 'ops-16',
      name: '강민준 강사',
      email: 'instructor.minjun@playdata.io',
      role: 'INSTRUCTOR',
      scope: 'DA 5기',
      status: 'active',
      lastLoginAt: '오늘 10:05',
      isSelf: false,
    },
    {
      id: 'ops-17',
      name: '조유나 멘토',
      email: 'mentor.yuna@playdata.io',
      role: 'MENTOR',
      scope: 'AI 캠프 21기 ML 팀',
      status: 'active',
      lastLoginAt: '어제 16:30',
      isSelf: false,
    },
    {
      id: 'ops-18',
      name: '신예은 강사',
      email: 'instructor.yeeun@playdata.io',
      role: 'INSTRUCTOR',
      scope: 'AI 캠프 22기 · AI 캠프 21기',
      status: 'active',
      lastLoginAt: '오늘 09:50',
      isSelf: false,
    },
    {
      id: 'ops-19',
      name: '권도현 멘토',
      email: 'mentor.dohyun@playdata.io',
      role: 'MENTOR',
      scope: 'AI 캠프 22기 추천 시스템 팀',
      status: 'inactive',
      lastLoginAt: '05-01 10:00',
      isSelf: false,
    },
    {
      id: 'ops-20',
      name: '배수아 강사',
      email: 'instructor.sua@playdata.io',
      role: 'INSTRUCTOR',
      scope: '담당 범위 없음',
      status: 'active',
      lastLoginAt: '05-20 13:00',
      isSelf: false,
    },
    {
      id: 'ops-21',
      name: '문지우 멘토',
      email: 'mentor.jiwoo@playdata.io',
      role: 'MENTOR',
      scope: 'DA 5기 시각화 팀',
      status: 'active',
      lastLoginAt: '오늘 08:55',
      isSelf: false,
    },
    {
      id: 'ops-22',
      name: '양하은 매니저',
      email: 'manager.haeun@playdata.io',
      role: 'MANAGER',
      scope: '전체 운영 · 모든 과정·기수',
      status: 'inactive',
      lastLoginAt: '05-05 09:00',
      isSelf: false,
    },
    {
      id: 'ops-23',
      name: '서준영 강사',
      email: 'instructor.junyoung@playdata.io',
      role: 'INSTRUCTOR',
      scope: 'DE 3기',
      status: 'invited',
      lastLoginAt: null,
      isSelf: false,
    },
    {
      id: 'ops-24',
      name: '남도경 멘토',
      email: 'mentor.dogyeong@playdata.io',
      role: 'MENTOR',
      scope: 'AI 캠프 20기 팀',
      status: 'active',
      lastLoginAt: '어제 18:20',
      isSelf: false,
    },
  ],
}

// ── 설정 감사 로그 (Figma 5190:11189) ──
const settingsAudit: SettingsAuditData = {
  summary: {
    total: 142,
    totalHint: '최근 30일',
    accounts: 38,
    accountsHint: '권한 부여·회수 포함',
    hrdKey: 12,
    hrdKeyHint: '등록·교체·폐기',
    courseConfig: 21,
    courseConfigHint: '기능 토글·정책',
    security: 4,
    securityHint: '실패·재시도 포함',
  },
  events: [
    {
      id: 'sa1',
      at: '05-27 09:05',
      actor: '김매니저',
      category: 'account',
      origin: '계정 관리',
      action: '강사 권한 부여',
      target: '이지훈 강사',
      result: 'success',
    },
    {
      id: 'sa2',
      at: '05-26 18:42',
      actor: '박매니저',
      category: 'course',
      origin: '교육 과정 설정',
      action: '기능 토글 변경',
      target: 'AI 캠프 22기 · 평판 ON',
      result: 'success',
    },
    {
      id: 'sa3',
      at: '05-26 14:21',
      actor: '김매니저',
      category: 'hrd',
      origin: 'HRD API Key',
      action: '키 교체',
      target: 'prod-key-2026Q2',
      result: 'success',
    },
    {
      id: 'sa4',
      at: '05-25 16:08',
      actor: '이매니저',
      category: 'course',
      origin: '교육 과정 추가',
      action: '신규 과정 생성',
      target: 'DA 5기',
      result: 'success',
    },
    {
      id: 'sa5',
      at: '05-24 11:30',
      actor: '김매니저',
      category: 'account',
      origin: '계정 관리',
      action: '계정 비활성화',
      target: '박멘토',
      result: 'success',
    },
    {
      id: 'sa6',
      at: '05-23 17:02',
      actor: '시스템',
      category: 'hrd',
      origin: 'HRD API Key',
      action: '연결 테스트',
      target: 'prod-key-2026Q2',
      result: 'failure',
    },
    {
      id: 'sa7',
      at: '05-22 10:15',
      actor: '박매니저',
      category: 'account',
      origin: '계정 관리',
      action: '임시 비밀번호 발급',
      target: '김효원 멘토',
      result: 'success',
    },
    {
      id: 'sa8',
      at: '05-21 09:40',
      actor: '김매니저',
      category: 'course',
      origin: '교육 과정 설정',
      action: '학습 정책 변경',
      target: 'AI 캠프 21기 · 출결 기준',
      result: 'success',
    },
    {
      id: 'sa9',
      at: '05-20 15:20',
      actor: '이매니저',
      category: 'course',
      origin: '교육 과정 추가',
      action: '신규 기수 등록',
      target: 'AI 캠프 23기',
      result: 'success',
    },
    {
      id: 'sa10',
      at: '05-19 09:10',
      actor: '김매니저',
      category: 'hrd',
      origin: 'HRD API Key',
      action: '키 폐기',
      target: '구 키 2025',
      result: 'success',
    },
    {
      id: 'sa11',
      at: '05-18 14:45',
      actor: '박매니저',
      category: 'account',
      origin: '계정 관리',
      action: '계정 생성',
      target: '신규 강사 초대',
      result: 'success',
    },
    {
      id: 'sa12',
      at: '05-17 11:00',
      actor: '김매니저',
      category: 'course',
      origin: '교육 과정 설정',
      action: '공개 정책 변경',
      target: 'DA 5기 · 증명서 반영 ON',
      result: 'success',
    },
    {
      id: 'sa13',
      at: '05-16 16:30',
      actor: '이매니저',
      category: 'account',
      origin: '계정 관리',
      action: '담당 범위 변경',
      target: '이지훈 강사',
      result: 'success',
    },
    {
      id: 'sa14',
      at: '05-15 10:20',
      actor: '시스템',
      category: 'hrd',
      origin: 'HRD API Key',
      action: '연결 테스트',
      target: 'prod-key-2026Q2',
      result: 'success',
    },
    {
      id: 'sa15',
      at: '05-14 09:05',
      actor: '김매니저',
      category: 'course',
      origin: '교육 과정 설정',
      action: '기능 토글 변경',
      target: 'DE 3기 · PLAY OFF',
      result: 'success',
    },
    {
      id: 'sa16',
      at: '05-13 17:40',
      actor: '박매니저',
      category: 'account',
      origin: '계정 관리',
      action: '계정 비활성화',
      target: '박강사',
      result: 'success',
    },
  ],
}

export const handlers = [
  http.get('/api/admin/settings/hub', () => ok<SettingsHubData>(hub)),
  http.get('/api/admin/settings/audit', () =>
    ok<SettingsAuditData>(settingsAudit),
  ),
  http.get('/api/admin/settings/accounts', () => ok<OpsAccountsData>(accounts)),
  // HRD API Key는 learning-service(:8082) 실연동 — dev proxy가 처리(MSW mock 제거).
  // 교육 과정 설정·추가(과정 목록/상세/검색/등록)도 learning-service 실연동 — dev proxy가 처리(mock 제거).
]
