import { http, HttpResponse } from 'msw'
import type { TsCaseDetail, TsListData } from './types'

// 트러블슈팅 mock — 기능 로컬. 자동 수집 규약: `export const handlers`.
// Figma 목록(360:1297)·상세(3283:5853) 시안 재현.
const ok = <T>(data: T) => HttpResponse.json({ data })

const mockList: TsListData = {
  stats: [
    {
      key: 'total',
      label: '총 사례',
      value: '12',
      unit: '건',
      sub: '상황·해결·결과 다 갖춤 가능',
      tone: 'brand',
      barPct: 100,
    },
    {
      key: 'certified',
      label: '인증 완료',
      value: '8',
      unit: '건',
      sub: '증명서 내 인증 사례 카드에 반영',
      tone: 'success',
      barPct: 67,
    },
    {
      key: 'independent',
      label: '독립 해결률',
      value: '83',
      unit: '%',
      sub: '독립 10건 · 동료 도움 2건',
      tone: 'warning',
      barPct: 83,
    },
    {
      key: 'avgdays',
      label: '평균 해결',
      value: '2.3',
      unit: '일',
      sub: '문제 발생 → 해결까지',
      tone: 'accent',
      barPct: 46,
    },
  ],
  filters: [
    { key: 'all', label: '전체', count: 12 },
    { key: 'DB', label: 'DB', count: 4 },
    { key: 'deploy', label: '배포·인프라', count: 3 },
    { key: 'perf', label: '성능', count: 2 },
    { key: 'net', label: '네트워크·API', count: 2 },
    { key: 'etc', label: '기타', count: 1 },
  ],
  statusFilters: [
    { key: 'certified', label: '인증 완료', count: 8, tone: 'success' },
    { key: 'reviewing', label: '검토 중', count: 3, tone: 'warning' },
    { key: 'draft', label: '작성 중', count: 1, tone: 'accent' },
  ],
  cases: [
    {
      id: 'ts1',
      category: 'DB',
      categoryKey: 'DB',
      categoryTone: 'info',
      status: 'certified',
      statusLabel: '인증 완료',
      independent: true,
      days: '3일',
      repLinked: true,
      accentTone: 'info',
      title: 'Kafka 컨슈머 리밸런싱으로 메시지 중복 처리',
      createdAt: '작성 2026-04-22',
      updatedAt: '최근 수정 2026-05-10',
      situation:
        '스케일아웃 시 컨슈머 리밸런싱이 발생하면서 동일 주문 이벤트가 두 번 처리되어 멱등성이 깨졌습니다.',
      resolution:
        '멱등성 보장키 + ack 처리 패턴 재설계, 외부 키 기반 dedup 테이블을 적용했습니다.',
      result: '중복 처리 0건/주 · 결제 실패율 8% → 0.4%.',
      tags: ['#Kafka', '#이벤트소싱', '#멱등성'],
      actionLabel: '사례 열기',
    },
    {
      id: 'ts2',
      category: '성능',
      categoryKey: 'perf',
      categoryTone: 'warning',
      status: 'reviewing',
      statusLabel: '검토 중',
      independent: true,
      days: '1일',
      repLinked: false,
      accentTone: 'warning',
      title: 'JPA N+1 쿼리로 주문 목록 응답 3초 지연',
      createdAt: '작성 2026-05-02',
      updatedAt: '최근 수정 2026-05-12',
      situation:
        '주문 목록 조회 시 연관 엔티티마다 추가 쿼리가 발생해 100건 기준 응답이 3초로 지연됐습니다.',
      resolution:
        'N+1 제거를 위해 @EntityGraph·fetch join을 적용하고 페이지네이션을 보정했습니다.',
      result: '응답시간 3초 → 380ms (-87%).',
      tags: ['#JPA', '#N+1', '#성능'],
      actionLabel: '사례 열기',
    },
    {
      id: 'ts3',
      category: 'DB',
      categoryKey: 'DB',
      categoryTone: 'info',
      status: 'draft',
      statusLabel: '작성 중',
      independent: false,
      days: '진행 중',
      repLinked: false,
      accentTone: 'accent',
      title: 'Redis 캐시 stampede로 DB 부하 급증',
      createdAt: '작성 2026-05-13',
      updatedAt: '최근 수정 2026-05-13',
      situation:
        '캐시 만료 직후 다수 요청이 동시에 DB로 몰리면서 커넥션 풀이 고갈됐습니다.',
      resolution:
        'stampede 방지를 위해 PER 알고리즘과 single-flight 락을 적용했습니다.',
      result: 'DB 부하 70% ↓ (작성 중).',
      tags: ['#Redis', '#캐시', '#stampede'],
      actionLabel: '이어 작성',
    },
    {
      id: 'ts4',
      category: 'DB',
      categoryKey: 'DB',
      categoryTone: 'info',
      status: 'certified',
      statusLabel: '인증 완료',
      independent: true,
      days: '2일',
      repLinked: false,
      accentTone: 'info',
      title: 'MySQL 갭 락 데드락으로 주문 저장 간헐 실패',
      createdAt: '작성 2026-04-10',
      updatedAt: '최근 수정 2026-04-30',
      situation:
        '동시 주문 저장 시 인접 키 범위에 갭 락이 겹쳐 데드락이 간헐적으로 발생했습니다.',
      resolution:
        '인덱스 접근 순서를 통일하고 트랜잭션 범위를 좁혀 락 경합을 제거했습니다.',
      result: '데드락 주당 14건 → 0건.',
      tags: ['#MySQL', '#데드락', '#트랜잭션'],
      actionLabel: '사례 열기',
    },
    {
      id: 'ts5',
      category: 'DB',
      categoryKey: 'DB',
      categoryTone: 'info',
      status: 'reviewing',
      statusLabel: '검토 중',
      independent: true,
      days: '1일',
      repLinked: false,
      accentTone: 'warning',
      title: '복합 인덱스 누락으로 검색 쿼리 풀스캔',
      createdAt: '작성 2026-05-06',
      updatedAt: '최근 수정 2026-05-11',
      situation:
        '검색 조건에 맞는 인덱스가 없어 수십만 행을 풀스캔하며 응답이 느려졌습니다.',
      resolution:
        '실행 계획을 분석해 (status, created_at) 복합 인덱스를 추가했습니다.',
      result: '검색 응답 1.8초 → 90ms.',
      tags: ['#인덱스', '#실행계획', '#쿼리튜닝'],
      actionLabel: '사례 열기',
    },
    {
      id: 'ts6',
      category: '배포·인프라',
      categoryKey: 'deploy',
      categoryTone: 'accent',
      status: 'certified',
      statusLabel: '인증 완료',
      independent: true,
      days: '3일',
      repLinked: true,
      accentTone: 'accent',
      title: 'API 인증 토큰 만료로 배포 후 요청 실패',
      createdAt: '작성 2026-03-28',
      updatedAt: '최근 수정 2026-04-15',
      situation:
        '배포 직후 모든 API가 401로 실패했습니다. 운영 환경에서 토큰 만료 시간이 즉시 지난 값으로 계산됐습니다.',
      resolution:
        '만료 시간 저장을 UTC 기준으로 통일하고 배포 환경 변수 검증 체크를 추가했습니다.',
      result: '재배포 후 401 오류 0건, 배포 체크리스트 추가.',
      tags: ['#JWT', '#타임존', '#배포검증'],
      actionLabel: '사례 열기',
    },
    {
      id: 'ts7',
      category: '배포·인프라',
      categoryKey: 'deploy',
      categoryTone: 'accent',
      status: 'reviewing',
      statusLabel: '검토 중',
      independent: false,
      days: '1일',
      repLinked: false,
      accentTone: 'warning',
      title: 'Docker 빌드 캐시 미스로 CI 시간 폭증',
      createdAt: '작성 2026-05-04',
      updatedAt: '최근 수정 2026-05-09',
      situation:
        '레이어 순서가 자주 바뀌어 빌드 캐시가 매번 무효화되며 CI가 12분으로 늘었습니다.',
      resolution:
        '의존성 설치 레이어를 분리하고 변경 빈도 순으로 Dockerfile을 재배치했습니다.',
      result: 'CI 빌드 12분 → 3분.',
      tags: ['#Docker', '#CI', '#캐시'],
      actionLabel: '사례 열기',
    },
    {
      id: 'ts8',
      category: '배포·인프라',
      categoryKey: 'deploy',
      categoryTone: 'accent',
      status: 'certified',
      statusLabel: '인증 완료',
      independent: true,
      days: '1일',
      repLinked: false,
      accentTone: 'accent',
      title: 'CloudFront 캐시 무효화 누락으로 구버전 노출',
      createdAt: '작성 2026-04-02',
      updatedAt: '최근 수정 2026-04-20',
      situation:
        '배포 후에도 일부 사용자에게 이전 번들이 노출돼 흰 화면이 발생했습니다.',
      resolution:
        '배포 파이프라인에 CloudFront invalidation 단계를 추가하고 파일명 해시를 적용했습니다.',
      result: '구버전 노출 신고 0건.',
      tags: ['#CloudFront', '#캐시무효화', '#배포'],
      actionLabel: '사례 열기',
    },
    {
      id: 'ts9',
      category: '성능',
      categoryKey: 'perf',
      categoryTone: 'warning',
      status: 'certified',
      statusLabel: '인증 완료',
      independent: true,
      days: '2일',
      repLinked: true,
      accentTone: 'warning',
      title: '번들 사이즈 과다로 초기 로딩 4초',
      createdAt: '작성 2026-03-20',
      updatedAt: '최근 수정 2026-04-08',
      situation:
        '단일 번들에 모든 라우트가 포함돼 초기 로딩이 4초까지 늘어졌습니다.',
      resolution:
        '라우트별 코드 스플리팅과 lazy import, 무거운 라이브러리 동적 로딩을 적용했습니다.',
      result: '초기 로딩 4초 → 1.2초, 번들 1.8MB → 540KB.',
      tags: ['#코드스플리팅', '#번들', '#Vite'],
      actionLabel: '사례 열기',
    },
    {
      id: 'ts10',
      category: '네트워크·API',
      categoryKey: 'net',
      categoryTone: 'brand',
      status: 'certified',
      statusLabel: '인증 완료',
      independent: false,
      days: '1일',
      repLinked: false,
      accentTone: 'brand',
      title: 'CORS 프리플라이트 누락으로 API 호출 차단',
      createdAt: '작성 2026-04-05',
      updatedAt: '최근 수정 2026-04-25',
      situation:
        '커스텀 헤더 요청에서 OPTIONS 프리플라이트가 차단돼 모든 호출이 실패했습니다.',
      resolution:
        '허용 헤더·메서드를 명시하고 프리플라이트 응답을 캐시하도록 설정했습니다.',
      result: 'API 차단 신고 0건.',
      tags: ['#CORS', '#프리플라이트', '#API'],
      actionLabel: '사례 열기',
    },
    {
      id: 'ts11',
      category: '네트워크·API',
      categoryKey: 'net',
      categoryTone: 'brand',
      status: 'certified',
      statusLabel: '인증 완료',
      independent: true,
      days: '2일',
      repLinked: false,
      accentTone: 'brand',
      title: 'WebSocket 재연결 폭주로 서버 부하 급증',
      createdAt: '작성 2026-04-12',
      updatedAt: '최근 수정 2026-05-01',
      situation:
        '네트워크 끊김 시 클라이언트가 즉시 재연결을 반복해 서버 커넥션이 폭증했습니다.',
      resolution:
        '지수 백오프 + 지터를 적용하고 최대 재시도 한도를 두었습니다.',
      result: '재연결 트래픽 92% ↓.',
      tags: ['#WebSocket', '#백오프', '#재연결'],
      actionLabel: '사례 열기',
    },
    {
      id: 'ts12',
      category: '기타',
      categoryKey: 'etc',
      categoryTone: 'success',
      status: 'certified',
      statusLabel: '인증 완료',
      independent: true,
      days: '1일',
      repLinked: false,
      accentTone: 'success',
      title: '타임존 불일치로 일별 통계 집계 오류',
      createdAt: '작성 2026-03-15',
      updatedAt: '최근 수정 2026-04-02',
      situation:
        'UTC로 저장된 시각을 로컬로 변환하지 않고 집계해 자정 경계의 통계가 어긋났습니다.',
      resolution: '집계 기준 시각을 KST로 통일하고 변환 유틸을 단일화했습니다.',
      result: '집계 오차 0건, 리포트 신뢰도 회복.',
      tags: ['#타임존', '#집계', '#KST'],
      actionLabel: '사례 열기',
    },
  ],
  shownLabel: '12건 중 12건 표시',
}

const mockCase: TsCaseDetail = {
  id: 'ts3',
  title: 'API 인증 토큰 만료로 배포 후 요청 실패',
  category: '배포·인프라',
  categoryTone: 'accent',
  status: 'draft',
  statusLabel: '작성 중',
  presentationLinked: false,
  independent: true,
  days: '3일',
  situation:
    '배포 직후 모든 API 요청이 401로 실패했습니다. 로컬에서는 정상 동작했지만 운영 환경에서 인증 토큰 만료 시간이 즉시 지난 값으로 계산되었습니다.',
  resolution:
    '서버 시간대 설정과 토큰 만료 계산 로직을 비교해 UTC/KST 변환 누락을 확인했습니다. 만료 시간 저장을 UTC 기준으로 통일하고 배포 환경 변수 검증 체크를 추가했습니다.',
  result:
    '재배포 후 401 오류가 사라졌고, 인증 실패 재현 테스트와 배포 체크리스트가 추가되었습니다. 같은 이슈 재발 시 배포 전 검증 단계에서 차단할 수 있습니다.',
  attachments: [
    { label: 'server-log.txt', kind: 'file' },
    { label: 'fix-pr 링크', kind: 'link' },
  ],
  checklist: [
    {
      label: '상황/해결/결과 입력 완료',
      status: { label: '완료', tone: 'success' },
    },
    { label: '첨부 근거 2개 등록', status: { label: '완료', tone: 'success' } },
    {
      label: '발표 프로젝트 연결 필요',
      status: { label: '필요', tone: 'warning' },
    },
    {
      label: '중복 인증 요청 없음',
      status: { label: '완료', tone: 'success' },
    },
  ],
  timeline: [
    {
      key: 'draft',
      label: '작성 중 (draft)',
      sub: '현재 상태',
      state: 'current',
    },
    {
      key: 'submitted',
      label: '검토 중 (submitted)',
      sub: '인증 요청 후 전환',
      state: 'todo',
    },
    {
      key: 'certified',
      label: '인증 완료 (certified)',
      sub: '강사 승인 후 잠금',
      state: 'todo',
    },
  ],
  certPresentation: 'Final LMS 프로젝트 · 중간 발표',
  certReviewer: '클라우드 배포 · 강사 검토',
  certChecklist: [
    '상황/해결/결과 3개 항목이 모두 작성됨',
    '발표 프로젝트 또는 교과목이 연결됨',
    '첨부 근거와 소요 일수가 확인됨',
    '동일 사례로 진행 중인 요청이 없음',
  ],
}

// 인증 완료 사례 상세 — 변경 제안 진입 컨텍스트(certified → 변경 제안만 수정 가능).
const mockCaseCertified: TsCaseDetail = {
  id: 'ts1',
  title: 'Kafka 컨슈머 리밸런싱으로 메시지 중복 처리',
  category: 'DB',
  categoryTone: 'info',
  status: 'certified',
  statusLabel: '인증 완료',
  presentationLinked: true,
  independent: true,
  days: '3일',
  situation:
    '스케일아웃 시 컨슈머 리밸런싱이 발생하면서 동일 주문 이벤트가 두 번 처리되어 멱등성이 깨졌습니다.',
  resolution:
    '멱등성 보장키 + ack 처리 패턴을 재설계하고, 외부 키 기반 dedup 테이블을 적용했습니다.',
  result:
    '중복 처리 0건/주 누적, 결제 실패율 8% → 0.4%. 같은 이벤트 그룹 중복도 제거했습니다.',
  attachments: [
    { label: 'kafka-consumer-config.yml', kind: 'file' },
    { label: 'fix-pr 링크', kind: 'link' },
  ],
  checklist: [
    {
      label: '상황/해결/결과 입력 완료',
      status: { label: '완료', tone: 'success' },
    },
    { label: '첨부 근거 2개 등록', status: { label: '완료', tone: 'success' } },
    {
      label: '발표 프로젝트 연결됨',
      status: { label: '완료', tone: 'success' },
    },
    { label: '인증 완료(잠금)', status: { label: '완료', tone: 'success' } },
  ],
  timeline: [
    { key: 'draft', label: '작성 중 (draft)', sub: '작성 완료', state: 'done' },
    {
      key: 'submitted',
      label: '검토 중 (submitted)',
      sub: '강사 검토 완료',
      state: 'done',
    },
    {
      key: 'certified',
      label: '인증 완료 (certified)',
      sub: '현재 상태 · 변경 제안으로만 수정',
      state: 'current',
    },
  ],
  certPresentation: 'Final LMS 프로젝트 · 중간 발표',
  certReviewer: '클라우드 배포 · 강사 검토',
  certChecklist: [
    '상황/해결/결과 3개 항목이 모두 작성됨',
    '발표 프로젝트 또는 교과목이 연결됨',
    '첨부 근거와 소요 일수가 확인됨',
    '동일 사례로 진행 중인 요청이 없음',
  ],
}

// 인증 완료 사례 id 집합 — 상세 분기에 사용.
const CERTIFIED_IDS = new Set([
  'ts1',
  'ts4',
  'ts6',
  'ts8',
  'ts9',
  'ts10',
  'ts11',
  'ts12',
])

export const handlers = [
  http.get('/api/student/troubleshooting', () => ok(mockList)),
  http.get('/api/student/troubleshooting/:id', ({ params }) =>
    ok(CERTIFIED_IDS.has(String(params.id)) ? mockCaseCertified : mockCase),
  ),
]
