import { http, HttpResponse } from 'msw'
import type { CourseMaterials, MaterialItem } from './types'

// "나의 과정" mock — 기능 로컬. 자동 수집 규약: `export const handlers`
// (mocks/handlers.ts 가 import.meta.glob 으로 자동 등록 → handlers.ts 안 건드림).
// 데이터는 Figma 강의 홈(165:27)·자료실(168:27) 시안을 재현.
const ok = <T>(data: T) => HttpResponse.json({ data })

// 학생 공유 자료가 쌓이도록 가변 배열로 둔다(공유 POST가 맨 앞에 prepend).
// 카테고리 칩 카운트·페이지 수는 항목 개수에서 파생(buildMaterials)되어 자료가 늘면 자동 반영된다.
const materialItems: MaterialItem[] = [
  {
    id: 'm1',
    fileType: 'PDF',
    title: 'JPA 영속성 컨텍스트 슬라이드',
    author: '강사 박지수',
    timeAgo: '2일 전',
    downloadCount: 42,
    sizeLabel: '2.4MB',
    favorited: true,
    canPreview: true,
    fileUrl: '/materials/sample.pdf',
  },
  {
    id: 'm2',
    fileType: 'DOC',
    title: '트랜잭션 매니저 설명 노트',
    author: '강사 박지수',
    timeAgo: '2일 전',
    downloadCount: 17,
    sizeLabel: '0.9MB',
    favorited: false,
    canPreview: false,
    fileUrl: '/materials/sample.docx',
  },
  {
    id: 'm3',
    fileType: 'ZIP',
    title: '9주차 실습 정답 코드',
    author: '강사 박지수',
    timeAgo: '3일 전',
    downloadCount: 35,
    sizeLabel: '1.2MB',
    favorited: false,
    canPreview: false,
    fileUrl: '/materials/sample.zip',
  },
  {
    id: 'm4',
    fileType: 'LINK',
    title: 'Spring 공식 트랜잭션 가이드 (외부)',
    author: '강사 박지수',
    timeAgo: '1주 전',
    favorited: false,
    canPreview: false,
    isExternalLink: true,
    fileUrl:
      'https://docs.spring.io/spring-framework/reference/data-access/transaction.html',
  },
  {
    id: 'm5',
    fileType: 'PDF',
    title: '9주차 연관관계 매핑 슬라이드',
    author: '강사 박지수',
    timeAgo: '1주 전',
    downloadCount: 38,
    sizeLabel: '3.1MB',
    favorited: true,
    canPreview: true,
    fileUrl: '/materials/sample.pdf',
  },
  {
    id: 'm6',
    fileType: 'PDF',
    title: '내가 겪었던 JPA N+1 문제 해결 경험',
    author: '김수강',
    timeAgo: '2일 전',
    downloadCount: 15,
    sizeLabel: '1.1MB',
    favorited: true,
    canPreview: true,
    fileUrl: '/materials/sample.pdf',
    ownedByMe: true,
  },
  {
    id: 'm7',
    fileType: 'DOC',
    title: '토픽 정리 — Spring Boot 시큐리티 토킹',
    author: '오태원',
    timeAgo: '3일 전',
    downloadCount: 6,
    sizeLabel: '0.8MB',
    favorited: false,
    canPreview: false,
    fileUrl: '/materials/sample.docx',
  },
  {
    id: 'm8',
    fileType: 'LINK',
    title: '백엔드 로드맵 (Roadmap.sh)',
    author: '오영빈',
    timeAgo: '2주 전',
    favorited: false,
    canPreview: false,
    isExternalLink: true,
    fileUrl: 'https://roadmap.sh/backend',
  },
  {
    id: 'm9',
    fileType: 'PDF',
    title: '스프링 트랜잭션 전파 옵션 정리',
    author: '강사 박지수',
    timeAgo: '4일 전',
    downloadCount: 28,
    sizeLabel: '2.0MB',
    favorited: false,
    canPreview: true,
    fileUrl: '/materials/sample.pdf',
  },
  {
    id: 'm10',
    fileType: 'PDF',
    title: 'AOP와 프록시 동작 원리',
    author: '강사 박지수',
    timeAgo: '5일 전',
    downloadCount: 21,
    sizeLabel: '1.8MB',
    favorited: false,
    canPreview: true,
    fileUrl: '/materials/sample.pdf',
  },
  {
    id: 'm11',
    fileType: 'DOC',
    title: 'JPA 영속성 전이·고아 객체 노트',
    author: '강사 박지수',
    timeAgo: '5일 전',
    downloadCount: 12,
    sizeLabel: '0.7MB',
    favorited: false,
    canPreview: false,
    fileUrl: '/materials/sample.docx',
  },
  {
    id: 'm12',
    fileType: 'PDF',
    title: 'QueryDSL 동적 쿼리 작성법',
    author: '강사 박지수',
    timeAgo: '1주 전',
    downloadCount: 33,
    sizeLabel: '2.6MB',
    favorited: false,
    canPreview: true,
    fileUrl: '/materials/sample.pdf',
  },
  {
    id: 'm13',
    fileType: 'PDF',
    title: '스프링 시큐리티 인증 흐름 슬라이드',
    author: '강사 박지수',
    timeAgo: '1주 전',
    downloadCount: 40,
    sizeLabel: '3.4MB',
    favorited: false,
    canPreview: true,
    fileUrl: '/materials/sample.pdf',
  },
  {
    id: 'm14',
    fileType: 'DOC',
    title: '테스트 코드 작성 가이드',
    author: '강사 박지수',
    timeAgo: '2주 전',
    downloadCount: 9,
    sizeLabel: '0.6MB',
    favorited: false,
    canPreview: false,
    fileUrl: '/materials/sample.docx',
  },
  {
    id: 'm15',
    fileType: 'ZIP',
    title: '10주차 실습 스켈레톤 코드',
    author: '강사 박지수',
    timeAgo: '3일 전',
    downloadCount: 47,
    sizeLabel: '0.5MB',
    favorited: false,
    canPreview: false,
    fileUrl: '/materials/sample.zip',
  },
  {
    id: 'm16',
    fileType: 'ZIP',
    title: '11주차 QueryDSL 실습 과제',
    author: '강사 박지수',
    timeAgo: '6일 전',
    downloadCount: 18,
    sizeLabel: '0.4MB',
    favorited: false,
    canPreview: false,
    fileUrl: '/materials/sample.zip',
  },
  {
    id: 'm17',
    fileType: 'PDF',
    title: '실습 환경 세팅 가이드',
    author: '강사 박지수',
    timeAgo: '2주 전',
    downloadCount: 25,
    sizeLabel: '1.5MB',
    favorited: false,
    canPreview: true,
    fileUrl: '/materials/sample.pdf',
  },
  {
    id: 'm18',
    fileType: 'LINK',
    title: 'Baeldung Spring 튜토리얼 (외부)',
    author: '강사 박지수',
    timeAgo: '2주 전',
    favorited: false,
    canPreview: false,
    isExternalLink: true,
    fileUrl: 'https://www.baeldung.com/spring-tutorial',
  },
  {
    id: 'm19',
    fileType: 'PDF',
    title: '백엔드 면접 예상 질문 모음',
    author: '강사 박지수',
    timeAgo: '3주 전',
    downloadCount: 51,
    sizeLabel: '1.9MB',
    favorited: false,
    canPreview: true,
    fileUrl: '/materials/sample.pdf',
  },
  {
    id: 'm20',
    fileType: 'DOC',
    title: '내가 정리한 Git 협업 플로우',
    author: '오영빈',
    timeAgo: '4일 전',
    downloadCount: 8,
    sizeLabel: '0.9MB',
    favorited: false,
    canPreview: false,
    fileUrl: '/materials/sample.docx',
  },
]

function buildMaterials(): CourseMaterials {
  return {
    totalCount: materialItems.length,
    shownCount: Math.min(8, materialItems.length),
    items: materialItems,
  }
}

export const handlers = [
  // 나의 과정 홈(/student/course)은 learning-service 실연동 — mock 제거(mocks.ts glob 미등록 → proxy).
  // 자료실 조회는 learning-service CohortMaterial 실연동 — VITE_REAL_AUTH=true면 mock 미등록 → proxy.
  // 학생 공유(POST)·삭제(DELETE)는 CohortMaterial 범위 밖이라 mock 유지.
  ...(import.meta.env.VITE_REAL_AUTH === 'true'
    ? []
    : [
        http.get('/api/student/course/materials', () =>
          ok<CourseMaterials>(buildMaterials()),
        ),
      ]),
  // 학생 공유 자료 삭제 — 본인 소유(ownedByMe)만 허용. 공식 자료는 403으로 막는다.
]
