import { http, HttpResponse } from 'msw'
import type {
  InstructorQuizListData,
  QuizFormDetail,
  QuizQuestionsData,
  QuizSubmissionsData,
  GradingDetail,
} from '@/shared/types'

// 기능별 mock — handlers.ts의 import.meta.glob('../features/**/mocks.ts')가 자동 수집(#37).
// 강사/운영 퀴즈 Main Flow (/instructor/quizzes*).
const ok = <T>(data: T) => HttpResponse.json({ data })

// ── §5 퀴즈 관리 목록 (Figma 1337:9753) ──
const quizList: InstructorQuizListData = {
  total: 4,
  manualPendingTotal: 15,
  items: [
    {
      id: 'quiz-algo-3',
      title: '알고리즘 기초 #3',
      cohortLabel: 'DA 4기',
      subject: '알고리즘',
      gradingMode: 'MANUAL',
      startAt: '2026-05-12',
      endAt: '2026-05-18',
      submitted: 18,
      targetCount: 24,
      manualPending: 9,
      visibility: 'published',
    },
    {
      id: 'quiz-sql-join',
      title: 'SQL JOIN 마스터',
      cohortLabel: 'DA 4기',
      subject: 'SQL',
      gradingMode: 'MIXED',
      startAt: '2026-05-08',
      endAt: '2026-05-14',
      submitted: 22,
      targetCount: 24,
      manualPending: 6,
      visibility: 'closed',
    },
    {
      id: 'quiz-react-hooks',
      title: 'React Hooks 실습',
      cohortLabel: 'FE 7기',
      subject: 'React',
      gradingMode: 'AUTO',
      startAt: '2026-05-18',
      endAt: '2026-05-25',
      submitted: 12,
      targetCount: 18,
      manualPending: 0,
      visibility: 'published',
    },
    {
      id: 'quiz-js-closure',
      title: 'JS 클로저·스코프 진단',
      cohortLabel: 'FE 7기',
      subject: 'JavaScript',
      gradingMode: 'AUTO',
      startAt: '2026-05-20',
      endAt: '2026-05-27',
      submitted: 0,
      targetCount: 18,
      manualPending: null,
      visibility: 'draft',
    },
  ],
}

// ── §6 퀴즈 생성/수정 (Figma 1338:9792) ──
const quizDetails: Record<string, QuizFormDetail> = {
  'quiz-algo-3': {
    id: 'quiz-algo-3',
    cohortId: 'c1',
    title: '알고리즘 기초 #3',
    cohortOption: 'DA 4기 · 알고리즘',
    description: '재귀·동적 계획법·그리디 기본 개념 확인.',
    startAt: '2026-05-12 09:00',
    endAt: '2026-05-18 23:59',
    timeLimitMin: 90,
    allowRetake: false,
    gradingMode: 'MANUAL',
    resultReveal: 'after_grading',
    shuffleQuestions: true,
    shuffleChoices: true,
    totalPoints: 100,
    questionCount: 5,
    submittedCount: 18,
    visibility: 'published',
  },
  'quiz-sql-join': {
    id: 'quiz-sql-join',
    cohortId: 'c1',
    title: 'SQL JOIN 마스터',
    cohortOption: 'DA 4기 · SQL',
    description: 'INNER/OUTER JOIN·GROUP BY 심화 진단.',
    startAt: '2026-05-08 09:00',
    endAt: '2026-05-14 23:59',
    timeLimitMin: 60,
    allowRetake: false,
    gradingMode: 'MIXED',
    resultReveal: 'after_close',
    shuffleQuestions: true,
    shuffleChoices: false,
    totalPoints: 100,
    questionCount: 8,
    submittedCount: 22,
    visibility: 'closed',
  },
  'quiz-react-hooks': {
    id: 'quiz-react-hooks',
    cohortId: 'c2',
    title: 'React Hooks 실습',
    cohortOption: 'FE 7기 · React',
    description: 'useState·useEffect·커스텀 훅 핵심 점검.',
    startAt: '2026-05-18 09:00',
    endAt: '2026-05-25 23:59',
    timeLimitMin: 0,
    allowRetake: true,
    gradingMode: 'AUTO',
    resultReveal: 'immediate',
    shuffleQuestions: true,
    shuffleChoices: true,
    totalPoints: 100,
    questionCount: 5,
    submittedCount: 12,
    visibility: 'published',
  },
  'quiz-js-closure': {
    id: 'quiz-js-closure',
    cohortId: 'c2',
    title: 'JS 클로저·스코프 진단',
    cohortOption: 'FE 7기 · JavaScript',
    description: '클로저·스코프·호이스팅 입문 진단 — 임시저장.',
    startAt: '2026-05-20 09:00',
    endAt: '2026-05-27 23:59',
    timeLimitMin: 30,
    allowRetake: true,
    gradingMode: 'AUTO',
    resultReveal: 'immediate',
    shuffleQuestions: false,
    shuffleChoices: false,
    totalPoints: 80,
    questionCount: 0,
    submittedCount: 0,
    visibility: 'draft',
  },
}

// ── §7 문제 관리 (Figma 1341:9831) ──
const quizQuestions: QuizQuestionsData = {
  quizTitle: '알고리즘 기초 #3',
  gradingMode: 'MANUAL',
  totalPoints: 100,
  targetPoints: 100,
  questions: [
    {
      id: 'q-1',
      order: 1,
      type: 'multiple_choice',
      points: 15,
      summary: '재귀 함수의 종료 조건',
      body: '재귀 함수의 종료 조건으로 올바른 것을 고르시오.',
      modelAnswer: '베이스 케이스가 항상 도달 가능해야 한다.',
      explanation: '종료 조건 누락은 무한 재귀로 이어진다.',
      category: '알고리즘 · 재귀',
      difficulty: 'easy',
      createdAt: '2026-05-12',
      updatedAt: '2026-05-14',
      respondedCount: 18,
      totalCount: 24,
      avgScore: 12.1,
      choices: [
        '입력 크기와 무관하게 항상 재귀를 호출한다',
        '베이스 케이스에서 재귀를 멈춘다',
        '항상 두 번 이상 재귀한다',
        '종료 조건이 필요 없다',
      ],
      answerKey: '1',
    },
    {
      id: 'q-2',
      order: 2,
      type: 'short_answer',
      points: 15,
      summary: '시간 복잡도 표기법',
      body: '최악의 경우 수행 시간을 표기하는 점근 표기법의 이름을 쓰시오.',
      modelAnswer: '빅오 표기법 (Big-O)',
      explanation: '상한 표기 — 빅오. 하한은 빅오메가, 상·하한은 빅세타.',
      category: '알고리즘 · 재귀',
      difficulty: 'easy',
      createdAt: '2026-05-12',
      updatedAt: '2026-05-12',
      respondedCount: 18,
      totalCount: 24,
      avgScore: 13.5,
      choices: [],
      answerKey: '빅오',
    },
    {
      id: 'q-3',
      order: 3,
      type: 'essay',
      points: 30,
      summary: 'DP vs 메모이제이션',
      body: '동적 계획법(DP)과 메모이제이션의 차이를 두 가지 이상의 관점에서 설명하시오.',
      modelAnswer:
        'Top-down(메모이제이션) vs Bottom-up(DP), 부분 문제 캐싱 범위 차이.',
      explanation: '메모이제이션은 깊은 재귀에서 스택 오버플로 위험.',
      category: '알고리즘 · DP',
      difficulty: 'hard',
      createdAt: '2026-05-12',
      updatedAt: '2026-05-17',
      respondedCount: 18,
      totalCount: 24,
      avgScore: 18.4,
      choices: [],
      answerKey: '',
    },
    {
      id: 'q-4',
      order: 4,
      type: 'fill_blank',
      points: 20,
      summary: '그리디 알고리즘의 ___ 선택',
      body: '그리디 알고리즘은 매 단계에서 ___ 선택을 한다.',
      modelAnswer: '국소 최적(locally optimal)',
      explanation: '그리디는 국소 최적이 전역 최적이 되는 구조에서만 성립.',
      category: '알고리즘 · 재귀',
      difficulty: 'normal',
      createdAt: '2026-05-12',
      updatedAt: '2026-05-13',
      respondedCount: 18,
      totalCount: 24,
      avgScore: 16.2,
      choices: [],
      answerKey: '["국소 최적"]',
    },
    {
      id: 'q-5',
      order: 5,
      type: 'essay',
      points: 20,
      summary: '시간 복잡도 분석 — 다음 코드의 O(?)',
      body: '이중 for 문 코드의 시간 복잡도를 빅오 표기로 나타내고 근거를 설명하시오.',
      modelAnswer: '시간 복잡도 O(n²) + 등차수열 합 근거 = 만점 20.',
      explanation: 'n + (n-1) + … + 1 = n(n+1)/2 → O(n²).',
      category: '알고리즘 · DP',
      difficulty: 'normal',
      createdAt: '2026-05-12',
      updatedAt: '2026-05-16',
      respondedCount: 18,
      totalCount: 24,
      avgScore: 14.8,
      choices: [],
      answerKey: '',
    },
  ],
}

// ── §8 제출 현황 (Figma 1343:9870) ──
const quizSubmissions: QuizSubmissionsData = {
  quizTitle: '알고리즘 기초 #3',
  totalPoints: 100,
  kpi: {
    submitted: 18,
    targetCount: 24,
    notSubmitted: 6,
    manualPending: 9,
    avgScore: 84.7,
  },
  rows: [
    {
      id: 'sub-1',
      studentName: '박지훈',
      cohortLabel: 'FE 7기',
      submitted: true,
      submittedAt: '05-17 21:14',
      score: 42,
      scoreFinal: false,
      gradingState: 'manual_pending',
      manualPendingCount: 3,
      feedbackEntered: false,
    },
    {
      id: 'sub-4',
      studentName: '김민준',
      cohortLabel: 'DA 4기',
      submitted: true,
      submittedAt: '05-16 22:30',
      score: 88,
      scoreFinal: true,
      gradingState: 'done',
      manualPendingCount: 0,
      feedbackEntered: true,
    },
    {
      id: 'sub-5',
      studentName: '이서연',
      cohortLabel: 'DA 4기',
      submitted: true,
      submittedAt: '05-17 18:02',
      score: 95,
      scoreFinal: true,
      gradingState: 'auto_done',
      manualPendingCount: 0,
      feedbackEntered: false,
    },
    {
      id: 'sub-6',
      studentName: '송하늘',
      cohortLabel: 'DA 4기',
      submitted: false,
      submittedAt: null,
      score: null,
      scoreFinal: false,
      gradingState: null,
      manualPendingCount: 0,
      feedbackEntered: false,
    },
  ],
}

// ── §9 수동 채점 (Figma 1345:9909) ──
const gradingDetail: GradingDetail = {
  submissionId: 'sub-1',
  studentName: '박지훈',
  cohortLabel: 'FE 7기',
  quizTitle: '알고리즘 기초 #3',
  submittedAt: '2026-05-17 21:14',
  totalScore: 100,
  provisionalScore: 27,
  totalManualCount: 2,
  items: [
    {
      questionId: 'q-3',
      index: 1,
      type: 'essay',
      points: 30,
      status: 'done',
      body: '동적 계획법(DP)과 메모이제이션의 차이를 설명하시오.',
      studentAnswer:
        '메모이제이션은 재귀 + 캐시(Top-down), DP는 반복문 + 테이블(Bottom-up)입니다.',
      rubric: '두 관점 + 예시 = 만점 30 / 한 관점 = 부분점수 20.',
      score: 27,
      feedback: '핵심 관점 정확. 예시 코드가 있었으면 더 좋았습니다.',
      feedbackVisible: true,
    },
    {
      questionId: 'q-5',
      index: 2,
      type: 'essay',
      points: 20,
      status: 'pending',
      body: '이중 for 문 코드의 시간 복잡도를 빅오 표기로 설명하시오.',
      studentAnswer: 'O(n²)입니다. 바깥/안쪽 루프가 각각 n번 도니까요.',
      rubric: '결과 O(n²) + 등차수열 합 근거 = 만점 20.',
      score: null,
      feedback: '',
      feedbackVisible: false,
    },
  ],
}

const fallbackDetail = quizDetails['quiz-algo-3']

export const handlers = [
  http.get('/api/instructor/quizzes', () =>
    ok<InstructorQuizListData>(quizList),
  ),
  // 구체 경로(questions·submissions)가 상세(:quizId)보다 먼저 매칭되도록 순서 유지.
  http.get('/api/instructor/quizzes/:quizId/questions', () =>
    ok<QuizQuestionsData>(quizQuestions),
  ),
  http.get(
    '/api/instructor/quizzes/:quizId/submissions/:submissionId/grade',
    () => ok<GradingDetail>(gradingDetail),
  ),
  http.get('/api/instructor/quizzes/:quizId/submissions', () =>
    ok<QuizSubmissionsData>(quizSubmissions),
  ),
  http.get('/api/instructor/quizzes/:quizId', ({ params }) => {
    const detail = quizDetails[String(params.quizId)] ?? fallbackDetail
    return ok<QuizFormDetail>(detail)
  }),
  // 생성/수정 — 생성된 듯한 상세를 반환.
  http.post('/api/instructor/quizzes', () =>
    ok<QuizFormDetail>({
      ...fallbackDetail,
      id: 'quiz-new',
      submittedCount: 0,
    }),
  ),
  http.patch('/api/instructor/quizzes/:quizId', ({ params }) => {
    const detail = quizDetails[String(params.quizId)] ?? fallbackDetail
    return ok<QuizFormDetail>({ ...detail, id: String(params.quizId) })
  }),
  http.delete('/api/instructor/quizzes/:quizId', () =>
    HttpResponse.json({ data: null }),
  ),
  // 문항 추가/수정/삭제.
  http.post('/api/instructor/quizzes/:quizId/questions', () => ok({})),
  http.patch('/api/instructor/quizzes/:quizId/questions/:questionId', () =>
    ok({}),
  ),
  http.delete('/api/instructor/quizzes/:quizId/questions/:questionId', () =>
    HttpResponse.json({ data: null }),
  ),
]
