import { http, HttpResponse } from 'msw'
import type {
  InstructorQuizListData,
  QuizFormDetail,
  QuizQuestionsData,
  QuizSubmissionsData,
  GradingDetail,
} from '@/shared/types'

// 기능별 mock — handlers.ts의 import.meta.glob('../features/**/mocks.ts')가 자동 수집(#37).
const ok = <T>(data: T) => HttpResponse.json({ data })

// ── §5 퀴즈 관리 목록 (Figma 1337:9753) ──
const quizList: InstructorQuizListData = {
  total: 14,
  manualPendingTotal: 15,
  items: [
    {
      id: 'quiz-algo-3',
      title: '알고리즘 기초 #3',
      cohortLabel: 'DA 4기',
      subject: '알고리즘',
      gradingMode: 'MANUAL',
      startAt: '2026-05-12',
      endAt: '2026-05-18',
      submitted: 18,
      targetCount: 24,
      manualPending: 9,
      visibility: 'published',
    },
    {
      id: 'quiz-data-clean',
      title: '데이터 정제 실습',
      cohortLabel: 'DA 4기',
      subject: '데이터분석',
      gradingMode: 'AUTO',
      startAt: '2026-05-10',
      endAt: '2026-05-15',
      submitted: 22,
      targetCount: 24,
      manualPending: 0,
      visibility: 'published',
    },
    {
      id: 'quiz-sql-window',
      title: 'SQL 윈도우 함수',
      cohortLabel: 'DA 4기',
      subject: 'SQL',
      gradingMode: 'MIXED',
      startAt: '2026-05-08',
      endAt: '2026-05-13',
      submitted: 20,
      targetCount: 24,
      manualPending: 0,
      visibility: 'closed',
    },
    {
      id: 'quiz-js-closure',
      title: 'JS 클로저 이해',
      cohortLabel: 'FE 7기',
      subject: 'JavaScript',
      gradingMode: 'MANUAL',
      startAt: '2026-05-15',
      endAt: '2026-05-22',
      submitted: 12,
      targetCount: 18,
      manualPending: 6,
      visibility: 'published',
    },
    {
      id: 'quiz-react-hooks',
      title: 'React Hooks 실습',
      cohortLabel: 'FE 7기',
      subject: 'React',
      gradingMode: 'AUTO',
      startAt: '2026-05-18',
      endAt: '2026-05-25',
      submitted: 0,
      targetCount: 18,
      manualPending: null,
      visibility: 'draft',
    },
  ],
}

// ── §6 퀴즈 생성/수정 (Figma 1338:9792) ──
const quizDetails: Record<string, QuizFormDetail> = {
  'quiz-algo-3': {
    id: 'quiz-algo-3',
    title: '알고리즘 기초 #3',
    cohortOption: 'DA 4기 · 알고리즘',
    description:
      '재귀·동적 계획법·그리디 기본 개념 확인. 마지막에 시간 복잡도 분석 1문항 포함.',
    startAt: '2026-05-12 09:00',
    endAt: '2026-05-18 23:59',
    timeLimitMin: 90,
    allowRetake: false,
    gradingMode: 'MANUAL',
    resultReveal: 'after_grading',
    shuffleQuestions: true,
    shuffleChoices: true,
    totalPoints: 100,
    questionCount: 5,
    submittedCount: 18,
    visibility: 'published',
  },
  'quiz-react-hooks': {
    id: 'quiz-react-hooks',
    title: 'React Hooks 실습',
    cohortOption: 'FE 7기 · React',
    description: 'useState·useEffect·커스텀 훅 기본기 점검.',
    startAt: '2026-05-18 09:00',
    endAt: '2026-05-25 23:59',
    timeLimitMin: 60,
    allowRetake: true,
    gradingMode: 'AUTO',
    resultReveal: 'immediate',
    shuffleQuestions: true,
    shuffleChoices: false,
    totalPoints: 100,
    questionCount: 8,
    submittedCount: 0,
    visibility: 'draft',
  },
}

// ── §7 문제 관리 (Figma 1341:9831) ──
const questions: QuizQuestionsData = {
  quizTitle: '알고리즘 기초 #3',
  gradingMode: 'MANUAL',
  totalPoints: 100,
  targetPoints: 100,
  questions: [
    {
      id: 'q-1',
      order: 1,
      type: 'multiple_choice',
      points: 15,
      summary: '재귀 함수의 종료 조건',
      body: '재귀 함수의 종료 조건을 두 가지 예시와 함께 설명하시오.',
      modelAnswer: '베이스 케이스 + 범위 종료 모두 명시 = 만점.',
      explanation: '종료 조건 누락은 무한 재귀로 이어진다.',
      category: '알고리즘 · 재귀',
      difficulty: 'easy',
      createdAt: '2026-05-12',
      updatedAt: '2026-05-14',
      respondedCount: 18,
      totalCount: 24,
      avgScore: 12.1,
    },
    {
      id: 'q-2',
      order: 2,
      type: 'short_answer',
      points: 15,
      summary: '시간 복잡도 표기법',
      body: '최악의 경우 수행 시간을 표기하는 점근 표기법의 이름을 쓰시오.',
      modelAnswer: '빅오 표기법 (Big-O)',
      explanation: '상한 표기 — 빅오. 하한은 빅오메가, 상·하한은 빅세타.',
      category: '알고리즘 · 재귀',
      difficulty: 'easy',
      createdAt: '2026-05-12',
      updatedAt: '2026-05-12',
      respondedCount: 18,
      totalCount: 24,
      avgScore: 13.4,
    },
    {
      id: 'q-3',
      order: 3,
      type: 'essay',
      points: 30,
      summary: '동적 계획법 vs 메모이제이션 차이 설명',
      body: '동적 계획법(DP)과 메모이제이션의 차이를 두 가지 이상의 관점에서 설명하시오. 예시 코드를 포함해도 좋습니다.',
      modelAnswer:
        '1) 메모이제이션은 Top-down + 재귀 + 캐시 / DP는 Bottom-up + 반복문 2) 메모이제이션은 부분 문제만 캐싱 / DP는 모든 부분 문제 테이블 채움 채점: 두 관점 + 예시 코드 = 만점 30 / 한 관점 + 코드 = 부분점수 20',
      explanation:
        '메모이제이션은 직관적이지만 깊은 재귀에서 스택 오버플로 위험. DP는 공간 최적화 가능.',
      category: '알고리즘 · DP',
      difficulty: 'hard',
      createdAt: '2026-05-12',
      updatedAt: '2026-05-17',
      respondedCount: 18,
      totalCount: 24,
      avgScore: 18.4,
    },
    {
      id: 'q-4',
      order: 4,
      type: 'fill_blank',
      points: 20,
      summary: '그리디 알고리즘의 ___ 선택',
      body: '그리디 알고리즘은 매 단계에서 ___ 선택을 한다.',
      modelAnswer: '국소 최적(locally optimal)',
      explanation: '그리디는 국소 최적이 전역 최적이 되는 구조에서만 성립.',
      category: '알고리즘 · 재귀',
      difficulty: 'normal',
      createdAt: '2026-05-12',
      updatedAt: '2026-05-13',
      respondedCount: 18,
      totalCount: 24,
      avgScore: 15.2,
    },
    {
      id: 'q-5',
      order: 5,
      type: 'essay',
      points: 20,
      summary: '시간 복잡도 분석 — 다음 코드의 O(?)',
      body: '다음 코드의 시간 복잡도를 빅오 표기로 나타내고 근거를 설명하시오.\n```python\nfor i in range(n):\n    for j in range(i, n):\n        print(i, j)\n```',
      modelAnswer:
        '시간 복잡도 O(n²) + 정확한 카운팅 근거(등차수열 합) = 만점 20 / 결과만 정답 = 10 / 결과만 + 일반론 = 12',
      explanation: 'n + (n-1) + … + 1 = n(n+1)/2 → O(n²).',
      category: '알고리즘 · DP',
      difficulty: 'normal',
      createdAt: '2026-05-12',
      updatedAt: '2026-05-16',
      respondedCount: 18,
      totalCount: 24,
      avgScore: 11.8,
    },
  ],
}

// ── §8 제출 현황 (Figma 1343:9870) ──
const submissions: QuizSubmissionsData = {
  quizTitle: '알고리즘 기초 #3',
  totalPoints: 100,
  kpi: {
    submitted: 18,
    targetCount: 24,
    notSubmitted: 6,
    manualPending: 9,
    avgScore: 84.7,
  },
  rows: [
    {
      id: 'sub-1',
      studentName: '박지훈',
      cohortLabel: 'FE 7기',
      submitted: true,
      submittedAt: '05-17 21:14',
      score: 42,
      scoreFinal: false,
      gradingState: 'manual_pending',
      manualPendingCount: 3,
      feedbackEntered: false,
    },
    {
      id: 'sub-2',
      studentName: '이서연',
      cohortLabel: 'DA 4기',
      submitted: true,
      submittedAt: '05-17 18:42',
      score: 38,
      scoreFinal: false,
      gradingState: 'manual_pending',
      manualPendingCount: 2,
      feedbackEntered: false,
    },
    {
      id: 'sub-3',
      studentName: '한소율',
      cohortLabel: 'FE 7기',
      submitted: true,
      submittedAt: '05-17 17:08',
      score: 45,
      scoreFinal: false,
      gradingState: 'manual_pending',
      manualPendingCount: 2,
      feedbackEntered: true,
    },
    {
      id: 'sub-4',
      studentName: '김민준',
      cohortLabel: 'DA 4기',
      submitted: true,
      submittedAt: '05-16 22:30',
      score: 88,
      scoreFinal: true,
      gradingState: 'done',
      manualPendingCount: 0,
      feedbackEntered: true,
    },
    {
      id: 'sub-5',
      studentName: '정도윤',
      cohortLabel: 'DA 4기',
      submitted: true,
      submittedAt: '05-15 20:01',
      score: 79,
      scoreFinal: true,
      gradingState: 'auto_done',
      manualPendingCount: 0,
      feedbackEntered: false,
    },
    {
      id: 'sub-6',
      studentName: '송하늘',
      cohortLabel: 'DA 4기',
      submitted: false,
      submittedAt: null,
      score: null,
      scoreFinal: false,
      gradingState: null,
      manualPendingCount: 0,
      feedbackEntered: false,
    },
  ],
}

// ── §9 수동 채점 (Figma 1345:9909) ──
const grading: GradingDetail = {
  submissionId: 'sub-1',
  studentName: '박지훈',
  cohortLabel: 'FE 7기',
  quizTitle: '알고리즘 기초 #3',
  submittedAt: '2026-05-17 21:14',
  totalScore: 100,
  provisionalScore: 42,
  totalManualCount: 3,
  items: [
    {
      questionId: 'q-1',
      index: 1,
      type: 'essay',
      points: 15,
      status: 'done',
      body: '재귀 함수의 종료 조건을 두 가지 예시와 함께 설명하시오.',
      studentAnswer:
        '재귀 함수의 종료 조건은 (1) 베이스 케이스 — 입력 크기가 0이거나 1일 때 반환 (예: factorial(0) = 1), (2) 인덱스가 배열 범위를 벗어날 때 (예: binarySearch에서 lo > hi).',
      rubric:
        '베이스 케이스 + 범위 종료 모두 명시 = 만점 15 / 한 가지만 = 8점 / 일반론만 = 4점.',
      score: 15,
      feedback:
        '재귀 종료 조건은 잘 작성됨. 시간 복잡도 표기에서 빅오와 빅세타 구분 미비 — 다음 강의에서 보완 예정.',
      feedbackVisible: true,
    },
    {
      questionId: 'q-3',
      index: 2,
      type: 'essay',
      points: 30,
      status: 'pending',
      body: '동적 계획법(DP)과 메모이제이션의 차이를 두 가지 이상의 관점에서 설명하시오. 예시 코드를 포함해도 좋습니다.',
      studentAnswer:
        '메모이제이션은 위에서 아래로 재귀적으로 호출하면서 결과를 저장하고, DP는 아래에서 위로 작은 문제부터 해결합니다. (예시 코드 미포함)',
      rubric:
        '1) 메모이제이션은 Top-down + 재귀 + 캐시 / DP는 Bottom-up + 반복문 2) 메모이제이션은 부분 문제만 캐싱 / DP는 모든 부분 문제 테이블 채움 채점: 두 관점 + 예시 코드 = 만점 30 / 한 관점 + 코드 = 부분점수 20 / 일반론만 = 10점',
      score: null,
      feedback: '',
      feedbackVisible: false,
    },
    {
      questionId: 'q-5',
      index: 3,
      type: 'essay',
      points: 20,
      status: 'in_progress',
      body: '다음 코드의 시간 복잡도를 빅오 표기로 나타내고 근거를 설명하시오.\n```python\nfor i in range(n):\n    for j in range(i, n):\n        print(i, j)\n```',
      studentAnswer:
        'O(n²)입니다. 이중 for문이라 그렇게 보이지만 정확히는 n*(n+1)/2번 실행됩니다.',
      rubric:
        '시간 복잡도 O(n²) + 정확한 카운팅 근거(등차수열 합) = 만점 20 / 결과만 정답 = 10 / 결과만 + 일반론 = 12',
      score: 12,
      feedback:
        '결과는 정답. 근거에 등차수열 합 공식을 명시하면 만점 가능 — 추가 학습 권장.',
      feedbackVisible: true,
    },
  ],
}

export const handlers = [
  http.get('/api/instructor/quizzes', () =>
    ok<InstructorQuizListData>(quizList),
  ),
  // 정적 세그먼트(questions/submissions)보다 상세(:quizId)가 늦게 매칭되도록 구체 경로 먼저.
  http.get('/api/instructor/quizzes/:quizId/questions', () =>
    ok<QuizQuestionsData>(questions),
  ),
  http.get(
    '/api/instructor/quizzes/:quizId/submissions/:submissionId/grade',
    () => ok<GradingDetail>(grading),
  ),
  http.get('/api/instructor/quizzes/:quizId/submissions', () =>
    ok<QuizSubmissionsData>(submissions),
  ),
  http.get('/api/instructor/quizzes/:quizId', ({ params }) => {
    const detail =
      quizDetails[String(params.quizId)] ?? quizDetails['quiz-algo-3']
    return ok<QuizFormDetail>(detail)
  }),
]
